# 配置thymeleaf
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_plan_helper?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create # 在每次连接数据库的时候,都会自动比对,如果发现实体类对象属性和表字段不一致,就会更新
    show-sql: true # 将sql语句输出到控制台及日志



